global:
  message: Welcome to order service prod environment

server:
  port: 8085
message: Hello from PROD!

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_prod
    username: root
    password: toor
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true